# Generated by Django 4.2.13 on 2026-05-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(blank=True, max_length=10)),
                ('material_number', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=20)),
                ('scope', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, help_text='kgCO2e = quantity × emission_factor', max_digits=18, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked'), ('FLAGGED', 'Flagged — needs review'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('reviewed_by_id', models.IntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by_id', models.IntegerField()),
                ('source_system', models.CharField(choices=[('sap_csv', 'SAP CSV (MB51)'), ('utility_csv', 'Utility Bill CSV'), ('travel_csv', 'Travel Booking CSV')], max_length=50)),
                ('raw_payload', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_uploads', to='ingestor.client')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField()),
                ('action', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('before_value', models.JSONField(blank=True, null=True)),
                ('after_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='ingestor.activityrow')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestor.client')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='activityrow',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_rows', to='ingestor.client'),
        ),
        migrations.AddField(
            model_name='activityrow',
            name='raw_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_rows', to='ingestor.rawupload'),
        ),
        migrations.CreateModel(
            name='PlantCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('site_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_codes', to='ingestor.client')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('client', 'code')},
            },
        ),
    ]
