# Generated by Django 4.2.13 on 2026-05-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrow',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityrow',
            name='edited_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityrow',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityrow',
            name='original_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
