# Generated by Django 4.2.13 on 2026-05-27 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestor', '0002_activityrow_edited_at_activityrow_edited_by_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('factor_key', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=6, max_digits=10)),
                ('unit_numerator', models.CharField(max_length=20)),
                ('unit_denominator', models.CharField(max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, help_text='Null = global default. Set = client-specific override.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='ingestor.client')),
            ],
            options={
                'ordering': ['-effective_from'],
                'unique_together': {('client', 'factor_key', 'effective_from')},
            },
        ),
        migrations.AddField(
            model_name='activityrow',
            name='emission_factor_ref',
            field=models.ForeignKey(blank=True, help_text='Versioned EmissionFactor used to compute co2e_kg.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_rows', to='ingestor.emissionfactor'),
        ),
    ]
