# Generated by Django 4.2.13 on 2026-05-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestor', '0003_emissionfactor_activityrow_emission_factor_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EDITED', 'Edited')], max_length=20),
        ),
    ]
